### ISSUE TITLE
Add getter function for assignments

### ISSUE THREAD

**Issue by mforets** [blegat/HybridSystems.jl#20]
Proposal: add "assignment" function as the getter function for reset maps:

```julia
assignment(hs::HybridSystem, t) = hs.resetmaps[symbol(hs, t)]
```

*Note.* If we add "ConstrainedMap" as proposed [MathematicalSystems#60](https://github.com/JuliaReach/MathematicalSystems.jl/issues/60#issue-406114195), then it is implemented as

```julia
assignment(hs::HybridSystem, t) = hs.resetmaps[symbol(hs, t)].map
```

Either way, i think it is useful to add this function because it is less implementation-dependent.

**Comment by schillic** [comment]
The second one is fine, but the first one is confusing because it does not give you the assignment.
