### ISSUE TITLE
Add getter function for the target mode

### ISSUE THREAD

**Issue by mforets** [blegat/HybridSystems.jl#23]
The target mode of the transition `t` in the `HS::HybridSystem` can be obtained as `HS.modes[target(HS, t)]`. How about adding a getter function named `target_mode(HS, t)`, or `dest(HS, t)`?

**Comment by blegat** [comment]
`target_mode` looks good. `dest` may be confused with the `LighGraphs` `src`/`dest` for edges

**Comment by schillic** [comment]
Is there a reason why `source_mode` is not needed?

**Comment by mforets** [comment]
Yes, why not: `source_mode(HS, t) = HS.modes[source(HS, t)]`. We only used `target_mode` [in this part](https://github.com/JuliaReach/Reachability.jl/blob/master/src/ReachSets/DiscretePost/LazyDiscretePost.jl#L127), but that functin could be useful elsewhere.
