### ISSUE TITLE
Make docs

### ISSUE THREAD

**Issue by mforets** [blegat/HybridSystems.jl#3]
i'd like to contribute with the docs. do you have any particular recommendation for its organization? it could be, e.g., `Library -> (Types, Methods)` as in [Systems.jl](https://juliareach.github.io/Systems.jl/latest/).

**Comment by blegat** [comment]
Thanks ! Yes, I like the way the documentation of Systems.jl is written and it makes sense to mimic it as it is an extension.

**Comment by mforets** [comment]
@JuliaRegistrator register()
